#_---------------------------------------------------------------------------_#
#                        Hackers Poulette (tidjee-dev)                        #
#_---------------------------------------------------------------------------_#

services:
  ###> PHP APACHE ###
  apache:
    build: ./docker/php-apache
    container_name: ${PROJECT_NAME}-app
    restart: on-failure
    ports:
      - "10000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php-apache/my-vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
      - phpmyadmin
      - adminer
  ###< PHP APACHE ###

  ###> MYSQL ###
  mysql:
    image: mysql
    container_name: ${PROJECT_NAME}-mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
  ###< MYSQL ###

  ###> PHPMYADMIN ###
  phpmyadmin:
    # image: phpmyadmin/phpmyadmin
    build: ./docker/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: on-failure
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
  ###< PHPMYADMIN ###

  ###> ADMINER ###
  adminer:
    image: adminer
    container_name: ${PROJECT_NAME}-adminer
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      ADMINER_DESIGN: "hydra"
    depends_on:
      - mysql
  ###< ADMINER ###
